-- ============================================
-- COMPREHENSIVE 500 QUESTIONS IMPORT
-- Ready for Supabase Database Import
-- Covers: IT, HR, Operations, Finance, Developers, Architects, 
--         Admin, Delivery Heads, Sales, Leadership, Directors, PMs, Trainers
-- ============================================

-- This script inserts 500 questions into survey_questions table
-- Questions are mapped to scales and factors using code references
-- Metadata includes role targeting and department information

INSERT INTO public.survey_questions (prompt, scale_id, factor_id, weight, reverse_scored, order_index, metadata)
SELECT 
  q.prompt,
  s.id as scale_id,
  f.id as factor_id,
  q.weight,
  q.reverse_scored,
  q.order_index,
  q.metadata::jsonb
FROM (VALUES

-- ============================================
-- SECTION 1: GENERAL IT & STAFFING (1-50)
-- ============================================
('How clear are your role expectations and responsibilities?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 1, '{"roles": ["all"], "departments": ["IT", "Staffing"]}'),
('How often do you receive recognition for doing good work?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 2, '{"roles": ["all"], "departments": ["IT"]}'),
('Do you have the materials and equipment needed to do your work right?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.0, false, 3, '{"roles": ["all"], "departments": ["IT"]}'),
('At work, do you have the opportunity to do what you do best every day?', 'GALLUP_Q12', 'GROWTH', 1.3, false, 4, '{"roles": ["all"], "departments": ["IT"]}'),
('In the last seven days, have you received recognition or praise for good work?', 'GALLUP_Q12', 'RECOGNITION', 1.1, false, 5, '{"roles": ["all"], "departments": ["IT"]}'),
('Does your supervisor, or someone at work, seem to care about you as a person?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 6, '{"roles": ["all"], "departments": ["IT"]}'),
('Is there someone at work who encourages your development?', 'GALLUP_Q12', 'GROWTH', 1.3, false, 7, '{"roles": ["all"], "departments": ["IT"]}'),
('At work, do your opinions seem to count?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 8, '{"roles": ["all"], "departments": ["IT"]}'),
('Does the mission/purpose of your company make you feel your job is important?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 9, '{"roles": ["all"], "departments": ["IT"]}'),
('Are your associates (fellow employees) committed to doing quality work?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.0, false, 10, '{"roles": ["all"], "departments": ["IT"]}'),
('Do you have a best friend at work?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.0, false, 11, '{"roles": ["all"], "departments": ["IT"]}'),
('In the last six months, has someone at work talked to you about your progress?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 12, '{"roles": ["all"], "departments": ["IT"]}'),
('How satisfied are you with your current work-life balance?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 13, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel overwhelmed by your workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.4, true, 14, '{"roles": ["all"], "departments": ["IT"]}'),
('How well do you understand how your work contributes to company goals?', 'GALLUP_Q12', 'BELONGING', 1.1, false, 15, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel stressed at work?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 16, '{"roles": ["all"], "departments": ["IT"]}'),
('How supported do you feel by your immediate team?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 17, '{"roles": ["all"], "departments": ["IT"]}'),
('How clear is the feedback you receive about your performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 18, '{"roles": ["all"], "departments": ["IT"]}'),
('How much autonomy do you have in how you complete your work?', 'JD_R', 'AUTONOMY', 1.3, false, 19, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel your contributions are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 20, '{"roles": ["all"], "departments": ["IT"]}'),
('How well does your manager support your professional growth?', 'GALLUP_Q12', 'GROWTH', 1.3, false, 21, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel disconnected from your team?', 'INCLUSION', 'BELONGING', 1.1, true, 22, '{"roles": ["all"], "departments": ["IT"]}'),
('How manageable is your current workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.4, false, 23, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you receive constructive feedback?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 24, '{"roles": ["all"], "departments": ["IT"]}'),
('How satisfied are you with opportunities for career advancement?', 'JD_R', 'GROWTH', 1.3, false, 25, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel burned out?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.4, true, 26, '{"roles": ["all"], "departments": ["IT"]}'),
('How included do you feel in team decision-making?', 'INCLUSION', 'AUTONOMY', 1.2, false, 27, '{"roles": ["all"], "departments": ["IT"]}'),
('How well does your team collaborate?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.1, false, 28, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel your work has meaning and purpose?', 'UWES', 'BELONGING', 1.3, false, 29, '{"roles": ["all"], "departments": ["IT"]}'),
('How energized do you feel about your work?', 'UWES', 'GROWTH', 1.2, false, 30, '{"roles": ["all"], "departments": ["IT"]}'),
('How dedicated are you to your work?', 'UWES', 'BELONGING', 1.2, false, 31, '{"roles": ["all"], "departments": ["IT"]}'),
('How absorbed do you get in your work?', 'UWES', 'GROWTH', 1.1, false, 32, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel you have too much to do?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 33, '{"roles": ["all"], "departments": ["IT"]}'),
('How well do you feel you can balance work and personal life?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 34, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel isolated at work?', 'INCLUSION', 'BELONGING', 1.1, true, 35, '{"roles": ["all"], "departments": ["IT"]}'),
('How well do you feel your voice is heard?', 'INCLUSION', 'AUTONOMY', 1.2, false, 36, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel little interest or pleasure in doing things?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 37, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel down, depressed, or hopeless?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 38, '{"roles": ["all"], "departments": ["IT"]}'),
('How satisfied are you with your current role?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 39, '{"roles": ["all"], "departments": ["IT"]}'),
('How well do you understand your career path?', 'JD_R', 'GROWTH', 1.3, false, 40, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you receive timely feedback?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 41, '{"roles": ["all"], "departments": ["IT"]}'),
('How supported do you feel in your professional development?', 'JD_R', 'GROWTH', 1.3, false, 42, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel your work is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 43, '{"roles": ["all"], "departments": ["IT"]}'),
('How well do you feel you fit with the company culture?', 'INCLUSION', 'BELONGING', 1.2, false, 44, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel you can be yourself at work?', 'INCLUSION', 'BELONGING', 1.1, false, 45, '{"roles": ["all"], "departments": ["IT"]}'),
('How well do you feel your team values diversity?', 'INCLUSION', 'BELONGING', 1.1, false, 46, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel excluded from important conversations?', 'INCLUSION', 'BELONGING', 1.1, true, 47, '{"roles": ["all"], "departments": ["IT"]}'),
('How well do you feel your manager understands your needs?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 48, '{"roles": ["all"], "departments": ["IT"]}'),
('How often do you feel micromanaged?', 'JD_R', 'AUTONOMY', 1.2, true, 49, '{"roles": ["all"], "departments": ["IT"]}'),
('How satisfied are you with your work environment?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 50, '{"roles": ["all"], "departments": ["IT"]}'),

-- ============================================
-- SECTION 2: HR & RECRUITMENT (51-100)
-- ============================================
('How well do you understand the recruitment process in your organization?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 51, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with the quality of candidates you interview?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 52, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel your hiring decisions are supported by leadership?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 53, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you can influence hiring strategy?', 'JD_R', 'AUTONOMY', 1.3, false, 54, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you receive feedback on your recruitment performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 55, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How manageable is your candidate pipeline?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 56, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel supported in onboarding new hires?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 57, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel your recruitment efforts are recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 58, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with the tools available for recruitment?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 59, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you understand diversity and inclusion goals in hiring?', 'INCLUSION', 'BELONGING', 1.2, false, 60, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel pressure to fill positions quickly?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 61, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you can balance quality vs speed in hiring?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 62, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you collaborate with hiring managers effectively?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 63, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with candidate experience in your process?', 'GALLUP_Q12', 'BELONGING', 1.1, false, 64, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you understand what managers need in candidates?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 65, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel your expertise in recruitment is valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 66, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel supported in learning new recruitment techniques?', 'JD_R', 'GROWTH', 1.3, false, 67, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel burned out from constant recruiting?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 68, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with your work-life balance in recruitment?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 69, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you can maintain relationships with candidates?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.1, false, 70, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you receive clear feedback on your hiring decisions?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 71, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you understand compensation and benefits packages?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 72, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel you can negotiate effectively for candidates?', 'JD_R', 'AUTONOMY', 1.2, false, 73, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with the support you receive from HR leadership?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 74, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you can influence employer branding?', 'JD_R', 'AUTONOMY', 1.2, false, 75, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel your recruitment metrics are meaningful?', 'GALLUP_Q12', 'BELONGING', 1.1, false, 76, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel supported in using recruitment technology?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 77, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel you can be creative in your recruitment approach?', 'JD_R', 'AUTONOMY', 1.2, false, 78, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with opportunities to grow in HR?', 'JD_R', 'GROWTH', 1.3, false, 79, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you understand the company culture for hiring?', 'INCLUSION', 'BELONGING', 1.2, false, 80, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel your hiring process is efficient?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 81, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you can advocate for candidates?', 'JD_R', 'AUTONOMY', 1.2, false, 82, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you receive recognition for successful placements?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 83, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with your team collaboration in HR?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 84, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you can balance multiple open positions?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 85, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel you have the resources needed for recruitment?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 86, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you understand the technical requirements for roles you fill?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 87, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel your recruitment strategy aligns with business goals?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 88, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with candidate feedback on your process?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.1, false, 89, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you can maintain work-life balance in recruitment?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 90, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel energized by finding great talent?', 'UWES', 'GROWTH', 1.2, false, 91, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How dedicated are you to improving the recruitment process?', 'UWES', 'BELONGING', 1.2, false, 92, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How absorbed do you get in candidate interviews?', 'UWES', 'GROWTH', 1.1, false, 93, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel you can make a difference in building teams?', 'UWES', 'BELONGING', 1.3, false, 94, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel supported in handling difficult hiring situations?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 95, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel your recruitment expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 96, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How satisfied are you with your professional development in HR?', 'JD_R', 'GROWTH', 1.3, false, 97, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you can influence hiring best practices?', 'JD_R', 'AUTONOMY', 1.2, false, 98, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How often do you feel you can be authentic in your recruitment approach?', 'INCLUSION', 'BELONGING', 1.1, false, 99, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),
('How well do you feel you understand what makes candidates successful?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 100, '{"roles": ["hr", "recruiter"], "departments": ["HR"]}'),

-- ============================================
-- SECTION 3: OPERATIONS (101-150)
-- ============================================
('How well do you understand operational processes in your organization?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 101, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with the efficiency of operational workflows?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 102, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel your operational improvements are implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 103, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel supported in optimizing processes?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 104, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you receive feedback on operational performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 105, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How manageable is your operational workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 106, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you can influence operational strategy?', 'JD_R', 'AUTONOMY', 1.3, false, 107, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel your operational expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 108, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with the tools available for operations?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 109, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you understand how operations impact other departments?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 110, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel pressure to maintain operational efficiency?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 111, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you can balance quality vs speed in operations?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 112, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you collaborate effectively across departments?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 113, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with process documentation?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 114, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you understand operational metrics?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 115, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel your operational insights are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 116, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel supported in learning new operational methods?', 'JD_R', 'GROWTH', 1.3, false, 117, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel burned out from operational demands?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 118, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with your work-life balance in operations?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 119, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you can maintain relationships with stakeholders?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.1, false, 120, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you receive clear feedback on operational improvements?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 121, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you understand resource allocation in operations?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 122, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel you can make decisions autonomously in operations?', 'JD_R', 'AUTONOMY', 1.2, false, 123, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with the support you receive from operations leadership?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 124, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you can influence operational best practices?', 'JD_R', 'AUTONOMY', 1.2, false, 125, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel your operational metrics are meaningful?', 'GALLUP_Q12', 'BELONGING', 1.1, false, 126, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel supported in using operational technology?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 127, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel you can be innovative in operations?', 'JD_R', 'AUTONOMY', 1.2, false, 128, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with opportunities to grow in operations?', 'JD_R', 'GROWTH', 1.3, false, 129, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you understand the company operations strategy?', 'INCLUSION', 'BELONGING', 1.2, false, 130, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel your operational processes are efficient?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 131, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you can advocate for operational improvements?', 'JD_R', 'AUTONOMY', 1.2, false, 132, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you receive recognition for operational excellence?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 133, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with your team collaboration in operations?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 134, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you can balance multiple operational priorities?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 135, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel you have the resources needed for operations?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 136, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you understand the technical aspects of operations?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 137, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel your operational strategy aligns with business goals?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 138, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with feedback on operational performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.1, false, 139, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you can maintain work-life balance in operations?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 140, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel energized by improving operations?', 'UWES', 'GROWTH', 1.2, false, 141, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How dedicated are you to operational excellence?', 'UWES', 'BELONGING', 1.2, false, 142, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How absorbed do you get in solving operational challenges?', 'UWES', 'GROWTH', 1.1, false, 143, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel you can make a difference in operations?', 'UWES', 'BELONGING', 1.3, false, 144, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel supported in handling operational crises?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 145, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel your operational expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 146, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How satisfied are you with your professional development in operations?', 'JD_R', 'GROWTH', 1.3, false, 147, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you can influence operational best practices?', 'JD_R', 'AUTONOMY', 1.2, false, 148, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How often do you feel you can be authentic in your operational approach?', 'INCLUSION', 'BELONGING', 1.1, false, 149, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),
('How well do you feel you understand what makes operations successful?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 150, '{"roles": ["operations", "admin"], "departments": ["Operations"]}'),

-- ============================================
-- SECTION 4: FULL STACK DEVELOPERS (151-200)
-- ============================================
('How satisfied are you with the code quality standards in your team?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 151, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can influence technical decisions?', 'JD_R', 'AUTONOMY', 1.3, false, 152, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in learning new technologies?', 'JD_R', 'GROWTH', 1.3, false, 153, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How manageable is your development workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.4, false, 154, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you receive code review feedback?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 155, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you understand the architecture of systems you work on?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 156, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your technical contributions are recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 157, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with the development tools and environment?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 158, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can balance frontend and backend work?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 159, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you collaborate effectively with other developers?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 160, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you understand the business context of your code?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 161, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel pressure from tight deadlines?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 162, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can write clean, maintainable code?', 'JD_R', 'AUTONOMY', 1.2, false, 163, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with testing practices in your team?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 164, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you receive constructive technical feedback?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 165, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in debugging complex issues?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 166, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel burned out from development work?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 167, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with your work-life balance as a developer?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 168, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can influence technical architecture?', 'JD_R', 'AUTONOMY', 1.3, false, 169, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your code is appreciated by the team?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 170, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you understand deployment and DevOps processes?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 171, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can make technical decisions autonomously?', 'JD_R', 'AUTONOMY', 1.2, false, 172, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with the support from your tech lead?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 173, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can influence development best practices?', 'JD_R', 'AUTONOMY', 1.2, false, 174, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your technical metrics are meaningful?', 'GALLUP_Q12', 'BELONGING', 1.1, false, 175, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in using new development tools?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 176, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can be innovative in your solutions?', 'JD_R', 'AUTONOMY', 1.2, false, 177, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with opportunities to grow as a developer?', 'JD_R', 'GROWTH', 1.3, false, 178, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you understand the product vision?', 'INCLUSION', 'BELONGING', 1.2, false, 179, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your development processes are efficient?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 180, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can advocate for technical improvements?', 'JD_R', 'AUTONOMY', 1.2, false, 181, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you receive recognition for technical achievements?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 182, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with your team collaboration in development?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 183, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can balance multiple development tasks?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 184, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you have the resources needed for development?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 185, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you understand the user impact of your code?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 186, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your development work aligns with business goals?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 187, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with feedback on your code quality?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.1, false, 188, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can maintain work-life balance as a developer?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 189, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel energized by solving technical challenges?', 'UWES', 'GROWTH', 1.2, false, 190, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How dedicated are you to writing quality code?', 'UWES', 'BELONGING', 1.2, false, 191, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How absorbed do you get in coding?', 'UWES', 'GROWTH', 1.1, false, 192, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can make a difference through your code?', 'UWES', 'BELONGING', 1.3, false, 193, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in handling production issues?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 194, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your technical expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 195, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with your professional development as a developer?', 'JD_R', 'GROWTH', 1.3, false, 196, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can influence technical standards?', 'JD_R', 'AUTONOMY', 1.2, false, 197, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can be creative in your technical solutions?', 'INCLUSION', 'BELONGING', 1.1, false, 198, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you understand what makes code maintainable?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 199, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can contribute to technical discussions?', 'INCLUSION', 'AUTONOMY', 1.2, false, 200, '{"roles": ["developer", "fullstack"], "departments": ["IT", "Engineering"]}'),

-- ============================================
-- SECTION 5: TRAINERS (201-300)
-- ============================================
('How well do you understand training needs in your organization?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 201, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training program effectiveness?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 202, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training improvements are implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 203, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel supported in designing training programs?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 204, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you receive feedback on training delivery?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 205, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How manageable is your training workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 206, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can influence training strategy?', 'JD_R', 'AUTONOMY', 1.3, false, 207, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 208, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training tools and platforms?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 209, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you understand how training impacts employee development?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 210, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel pressure to deliver effective training?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 211, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can balance different learning styles?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 212, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you collaborate effectively with subject matter experts?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 213, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training materials and content?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 214, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you understand adult learning principles?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 215, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training recommendations are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 216, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel supported in learning new training methods?', 'JD_R', 'GROWTH', 1.3, false, 217, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel burned out from training delivery?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 218, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with your work-life balance as a trainer?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 219, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can engage diverse audiences?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 220, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you receive clear feedback on training effectiveness?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 221, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you understand training metrics and ROI?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 222, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can make training decisions autonomously?', 'JD_R', 'AUTONOMY', 1.2, false, 223, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with the support from training leadership?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 224, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can influence training best practices?', 'JD_R', 'AUTONOMY', 1.2, false, 225, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training metrics are meaningful?', 'GALLUP_Q12', 'BELONGING', 1.1, false, 226, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel supported in using training technology?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 227, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can be innovative in training delivery?', 'JD_R', 'AUTONOMY', 1.2, false, 228, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with opportunities to grow as a trainer?', 'JD_R', 'GROWTH', 1.3, false, 229, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you understand the company training strategy?', 'INCLUSION', 'BELONGING', 1.2, false, 230, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training processes are efficient?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 231, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can advocate for training improvements?', 'JD_R', 'AUTONOMY', 1.2, false, 232, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you receive recognition for training excellence?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 233, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with your collaboration with trainees?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 234, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can balance multiple training programs?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 235, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you have the resources needed for training?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 236, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you understand e-learning and virtual training platforms?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 237, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training strategy aligns with business goals?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 238, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with feedback on training outcomes?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.1, false, 239, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can maintain work-life balance as a trainer?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 240, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel energized by training delivery?', 'UWES', 'GROWTH', 1.2, false, 241, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How dedicated are you to training excellence?', 'UWES', 'BELONGING', 1.2, false, 242, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How absorbed do you get in designing training programs?', 'UWES', 'GROWTH', 1.1, false, 243, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can make a difference through training?', 'UWES', 'BELONGING', 1.3, false, 244, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel supported in handling difficult training situations?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 245, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 246, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with your professional development as a trainer?', 'JD_R', 'GROWTH', 1.3, false, 247, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can influence training methodologies?', 'JD_R', 'AUTONOMY', 1.2, false, 248, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can be authentic in your training style?', 'INCLUSION', 'BELONGING', 1.1, false, 249, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you understand what makes training successful?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 250, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can adapt training to different audiences?', 'JD_R', 'AUTONOMY', 1.2, false, 251, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training evaluation methods?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.1, false, 252, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can measure training impact?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 253, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training content is up-to-date?', 'JD_R', 'GROWTH', 1.2, false, 254, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel supported in creating engaging training materials?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 255, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can handle challenging training scenarios?', 'JD_R', 'AUTONOMY', 1.2, false, 256, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training scheduling and logistics?', 'JD_R', 'WORKLOAD_PRESSURE', 1.1, false, 257, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can build rapport with trainees?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 258, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training delivery is effective?', 'UWES', 'GROWTH', 1.2, false, 259, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can facilitate group learning?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 260, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can create inclusive training environments?', 'INCLUSION', 'BELONGING', 1.2, false, 261, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training technology and platforms?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 262, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can assess training needs?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 263, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training programs meet learning objectives?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 264, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel supported in continuous improvement of training?', 'JD_R', 'GROWTH', 1.3, false, 265, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can inspire learning in others?', 'UWES', 'BELONGING', 1.3, false, 266, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training program variety?', 'JD_R', 'AUTONOMY', 1.1, false, 267, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can customize training for different roles?', 'JD_R', 'AUTONOMY', 1.2, false, 268, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training expertise contributes to company success?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 269, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can maintain enthusiasm in training delivery?', 'UWES', 'GROWTH', 1.2, false, 270, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel you can handle training feedback constructively?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 271, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training support resources?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 272, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can track training progress effectively?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 273, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training methods are innovative?', 'JD_R', 'AUTONOMY', 1.2, false, 274, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can create memorable learning experiences?', 'UWES', 'BELONGING', 1.3, false, 275, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training follow-up and reinforcement?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.1, false, 276, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can address different skill levels?', 'JD_R', 'AUTONOMY', 1.2, false, 277, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training delivery is engaging?', 'UWES', 'GROWTH', 1.2, false, 278, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can manage training logistics efficiently?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 279, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training programs drive behavior change?', 'UWES', 'BELONGING', 1.3, false, 280, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training collaboration with departments?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 281, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can adapt to virtual training environments?', 'JD_R', 'GROWTH', 1.2, false, 282, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training content is relevant?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 283, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can measure training ROI?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 284, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training program scalability?', 'JD_R', 'AUTONOMY', 1.1, false, 285, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training expertise is sought after?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 286, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can create comprehensive training curricula?', 'JD_R', 'AUTONOMY', 1.3, false, 287, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel energized by seeing trainees succeed?', 'UWES', 'GROWTH', 1.3, false, 288, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can provide constructive training feedback?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 289, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training program outcomes?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 290, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can stay current with training trends?', 'JD_R', 'GROWTH', 1.3, false, 291, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training programs are well-received?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 292, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can handle training program changes?', 'JD_R', 'AUTONOMY', 1.2, false, 293, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training program support from management?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 294, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training delivery improves over time?', 'JD_R', 'GROWTH', 1.2, false, 295, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can create training partnerships?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 296, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training programs meet business needs?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 297, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How well do you feel you can evaluate training effectiveness?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 298, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How satisfied are you with training program innovation?', 'JD_R', 'AUTONOMY', 1.2, false, 299, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),
('How often do you feel your training expertise makes a lasting impact?', 'UWES', 'BELONGING', 1.4, false, 300, '{"roles": ["trainer", "training_specialist"], "departments": ["HR", "Training"]}'),

-- ============================================
-- SECTION 6: FINANCE & ACCOUNTS (301-350)
-- ============================================
('How well do you understand financial processes in your organization?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 301, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with the accuracy of financial reporting?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 302, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel your financial insights are implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 303, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel supported in financial analysis?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 304, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you receive feedback on financial performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 305, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How manageable is your financial workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 306, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you can influence financial strategy?', 'JD_R', 'AUTONOMY', 1.3, false, 307, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel your financial expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 308, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with the tools available for financial work?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 309, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you understand how finance impacts other departments?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 310, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel pressure during month-end closing?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 311, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you can balance accuracy vs speed in financial work?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 312, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you collaborate effectively with other departments on budgets?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 313, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with financial documentation standards?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 314, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you understand financial metrics and KPIs?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 315, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel your financial recommendations are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 316, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel supported in learning new financial regulations?', 'JD_R', 'GROWTH', 1.3, false, 317, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel burned out from financial deadlines?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 318, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with your work-life balance in finance?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 319, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you can maintain relationships with auditors?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.1, false, 320, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you receive clear feedback on financial reporting?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 321, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you understand budget allocation processes?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 322, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel you can make decisions autonomously in finance?', 'JD_R', 'AUTONOMY', 1.2, false, 323, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with the support you receive from finance leadership?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 324, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you can influence financial best practices?', 'JD_R', 'AUTONOMY', 1.2, false, 325, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel your financial metrics are meaningful?', 'GALLUP_Q12', 'BELONGING', 1.1, false, 326, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel supported in using financial technology?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 327, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel you can be innovative in financial processes?', 'JD_R', 'AUTONOMY', 1.2, false, 328, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with opportunities to grow in finance?', 'JD_R', 'GROWTH', 1.3, false, 329, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you understand the company financial strategy?', 'INCLUSION', 'BELONGING', 1.2, false, 330, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel your financial processes are efficient?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 331, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you can advocate for financial improvements?', 'JD_R', 'AUTONOMY', 1.2, false, 332, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you receive recognition for financial excellence?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 333, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with your team collaboration in finance?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 334, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you can balance multiple financial priorities?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 335, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel you have the resources needed for financial work?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 336, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you understand the technical aspects of accounting systems?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 337, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel your financial strategy aligns with business goals?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 338, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with feedback on financial performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.1, false, 339, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you can maintain work-life balance in finance?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 340, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel energized by financial analysis?', 'UWES', 'GROWTH', 1.2, false, 341, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How dedicated are you to financial accuracy?', 'UWES', 'BELONGING', 1.2, false, 342, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How absorbed do you get in financial reporting?', 'UWES', 'GROWTH', 1.1, false, 343, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel you can make a difference through financial insights?', 'UWES', 'BELONGING', 1.3, false, 344, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel supported in handling financial audits?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 345, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel your financial expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 346, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How satisfied are you with your professional development in finance?', 'JD_R', 'GROWTH', 1.3, false, 347, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you can influence financial best practices?', 'JD_R', 'AUTONOMY', 1.2, false, 348, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How often do you feel you can be authentic in your financial approach?', 'INCLUSION', 'BELONGING', 1.1, false, 349, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}'),
('How well do you feel you understand what makes financial processes successful?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 350, '{"roles": ["finance", "accountant"], "departments": ["Finance"]}')

) AS q(prompt, scale_code, factor_code, weight, reverse_scored, order_index, metadata)
JOIN public.survey_scales s ON s.code = q.scale_code
JOIN public.survey_factors f ON f.code = q.factor_code
ON CONFLICT DO NOTHING;

-- ============================================
-- SECTION 6: ARCHITECTS (351-400)
-- ============================================
('How well do you understand the overall system architecture?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 351, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with architectural decision-making processes?', 'JD_R', 'AUTONOMY', 1.3, false, 352, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your architectural vision is implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.3, false, 353, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in designing scalable systems?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 354, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you receive feedback on architectural designs?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 355, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How manageable is your architectural workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 356, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can influence technical strategy?', 'JD_R', 'AUTONOMY', 1.4, false, 357, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your architectural expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 358, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with the tools available for architecture work?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 359, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you understand how architecture impacts business outcomes?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 360, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel pressure to make quick architectural decisions?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 361, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can balance innovation vs stability?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 362, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you collaborate effectively with development teams?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 363, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with architectural documentation standards?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 364, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you understand emerging technologies?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 365, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your architectural recommendations are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 366, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in learning new architectural patterns?', 'JD_R', 'GROWTH', 1.3, false, 367, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel burned out from architectural complexity?', 'PHQ2', 'WORKLOAD_PRESSURE', 1.3, true, 368, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with your work-life balance as an architect?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 369, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can mentor other architects?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 370, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you receive clear feedback on architectural decisions?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 371, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you understand cloud architecture principles?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 372, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can make architectural decisions autonomously?', 'JD_R', 'AUTONOMY', 1.3, false, 373, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with the support from technical leadership?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.2, false, 374, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can influence architectural best practices?', 'JD_R', 'AUTONOMY', 1.3, false, 375, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your architectural metrics are meaningful?', 'GALLUP_Q12', 'BELONGING', 1.1, false, 376, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in using architecture tools?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 377, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can be innovative in architecture?', 'JD_R', 'AUTONOMY', 1.3, false, 378, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with opportunities to grow as an architect?', 'JD_R', 'GROWTH', 1.3, false, 379, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you understand the product architecture vision?', 'INCLUSION', 'BELONGING', 1.2, false, 380, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your architectural processes are efficient?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 381, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can advocate for architectural improvements?', 'JD_R', 'AUTONOMY', 1.3, false, 382, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you receive recognition for architectural excellence?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 383, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with your collaboration with other architects?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 384, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can balance multiple architectural priorities?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 385, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you have the resources needed for architecture?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 386, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you understand security architecture principles?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 387, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your architecture aligns with business goals?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 388, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with feedback on architectural designs?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 389, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can maintain work-life balance as an architect?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 390, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel energized by architectural challenges?', 'UWES', 'GROWTH', 1.2, false, 391, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How dedicated are you to architectural excellence?', 'UWES', 'BELONGING', 1.2, false, 392, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How absorbed do you get in architectural design?', 'UWES', 'GROWTH', 1.1, false, 393, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can make a difference through architecture?', 'UWES', 'BELONGING', 1.3, false, 394, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in handling architectural challenges?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 395, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your architectural expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 396, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with your professional development as an architect?', 'JD_R', 'GROWTH', 1.3, false, 397, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can influence architectural standards?', 'JD_R', 'AUTONOMY', 1.3, false, 398, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How often do you feel you can be creative in architectural solutions?', 'INCLUSION', 'BELONGING', 1.2, false, 399, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you understand what makes architecture successful?', 'GALLUP_Q12', 'AUTONOMY', 1.3, false, 400, '{"roles": ["architect"], "departments": ["IT", "Engineering"]}'),

-- ============================================
-- SECTION 7: OFFICE ADMIN (401-420)
-- ============================================
('How well do you understand administrative processes?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 401, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How satisfied are you with office management efficiency?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 402, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How often do you feel your administrative improvements are implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 403, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How well do you feel supported in office operations?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 404, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How often do you receive feedback on administrative work?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 405, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How manageable is your administrative workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 406, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How well do you feel you can influence office policies?', 'JD_R', 'AUTONOMY', 1.2, false, 407, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How often do you feel your administrative expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 408, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How satisfied are you with office facilities and equipment?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 409, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How well do you understand how admin supports other departments?', 'GALLUP_Q12', 'BELONGING', 1.2, false, 410, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How often do you feel pressure from multiple administrative requests?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 411, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How well do you feel you can balance multiple admin tasks?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 412, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How often do you collaborate effectively with all departments?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 413, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How satisfied are you with administrative documentation?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 414, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How well do you feel you understand office management metrics?', 'GALLUP_Q12', 'AUTONOMY', 1.1, false, 415, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How often do you feel your administrative insights are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 416, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How well do you feel supported in learning new admin tools?', 'JD_R', 'GROWTH', 1.2, false, 417, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How satisfied are you with your work-life balance in admin?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 418, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How well do you feel you can maintain relationships with vendors?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.1, false, 419, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),
('How often do you feel your administrative work makes a difference?', 'UWES', 'BELONGING', 1.2, false, 420, '{"roles": ["admin", "office_admin"], "departments": ["Operations", "Admin"]}'),

-- ============================================
-- SECTION 8: DELIVERY HEADS (421-440)
-- ============================================
('How well do you understand delivery processes and timelines?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 421, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How satisfied are you with delivery team performance?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 422, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How often do you feel your delivery strategies are implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.3, false, 423, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How well do you feel supported in managing delivery teams?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 424, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How often do you receive feedback on delivery performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 425, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How manageable is your delivery workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 426, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How well do you feel you can influence delivery strategy?', 'JD_R', 'AUTONOMY', 1.3, false, 427, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How often do you feel your delivery expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 428, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How satisfied are you with delivery tools and systems?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 429, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How well do you understand how delivery impacts customer satisfaction?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 430, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How often do you feel pressure to meet delivery deadlines?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 431, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How well do you feel you can balance quality vs speed in delivery?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 432, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How often do you collaborate effectively with cross-functional teams?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 433, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How satisfied are you with delivery metrics and KPIs?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 434, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How well do you feel you understand delivery best practices?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 435, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How often do you feel your delivery improvements are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 436, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How well do you feel supported in optimizing delivery processes?', 'JD_R', 'GROWTH', 1.3, false, 437, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How satisfied are you with your work-life balance as a delivery head?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 438, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How well do you feel you can mentor delivery team members?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 439, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),
('How often do you feel you can make a difference in delivery outcomes?', 'UWES', 'BELONGING', 1.3, false, 440, '{"roles": ["delivery_head", "delivery_manager"], "departments": ["Operations", "Delivery"]}'),

-- ============================================
-- SECTION 9: SALES HEADS (441-460)
-- ============================================
('How well do you understand sales processes and strategies?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 441, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How satisfied are you with sales team performance?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 442, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How often do you feel your sales strategies are implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.3, false, 443, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How well do you feel supported in managing sales teams?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 444, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How often do you receive feedback on sales performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 445, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How manageable is your sales workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 446, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How well do you feel you can influence sales strategy?', 'JD_R', 'AUTONOMY', 1.3, false, 447, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How often do you feel your sales expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 448, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How satisfied are you with sales tools and CRM systems?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 449, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How well do you understand how sales impacts business growth?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 450, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How often do you feel pressure to meet sales targets?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 451, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How well do you feel you can balance relationship building vs closing deals?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 452, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How often do you collaborate effectively with marketing teams?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 453, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How satisfied are you with sales metrics and KPIs?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 454, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How well do you feel you understand customer needs?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 455, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How often do you feel your sales improvements are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 456, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How well do you feel supported in learning new sales techniques?', 'JD_R', 'GROWTH', 1.3, false, 457, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How satisfied are you with your work-life balance as a sales head?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 458, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How well do you feel you can mentor sales team members?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 459, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),
('How often do you feel energized by closing deals?', 'UWES', 'GROWTH', 1.2, false, 460, '{"roles": ["sales_head", "sales_manager"], "departments": ["Sales"]}'),

-- ============================================
-- SECTION 10: STRATEGIC LEADERSHIP/DIRECTORS (461-480)
-- ============================================
('How well do you understand the strategic direction of the company?', 'GALLUP_Q12', 'AUTONOMY', 1.3, false, 461, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How satisfied are you with strategic decision-making processes?', 'JD_R', 'AUTONOMY', 1.3, false, 462, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How often do you feel your strategic vision is implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.4, false, 463, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How well do you feel supported by the board and stakeholders?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 464, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How often do you receive feedback on strategic decisions?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 465, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How manageable is your strategic workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 466, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How well do you feel you can influence company direction?', 'JD_R', 'AUTONOMY', 1.4, false, 467, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How often do you feel your leadership is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 468, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How satisfied are you with strategic planning tools?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 469, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How well do you understand market dynamics and competition?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 470, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How often do you feel pressure from strategic responsibilities?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, true, 471, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How well do you feel you can balance short-term vs long-term goals?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 472, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How often do you collaborate effectively with other executives?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 473, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How satisfied are you with strategic metrics and KPIs?', 'GALLUP_Q12', 'SOCIAL_SUPPORT', 1.1, false, 474, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How well do you feel you understand organizational culture?', 'GALLUP_Q12', 'AUTONOMY', 1.3, false, 475, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How often do you feel your strategic insights are valued?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 476, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How well do you feel supported in developing leadership skills?', 'JD_R', 'GROWTH', 1.3, false, 477, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How satisfied are you with your work-life balance as a director?', 'JD_R', 'WORK_LIFE_BALANCE', 1.3, false, 478, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How well do you feel you can mentor other leaders?', 'INCLUSION', 'SOCIAL_SUPPORT', 1.2, false, 479, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),
('How often do you feel you can make a significant impact?', 'UWES', 'BELONGING', 1.4, false, 480, '{"roles": ["director", "strategic_leadership", "executive"], "departments": ["Leadership"]}'),

-- ============================================
-- SECTION 11: PROJECT MANAGERS - TECHNICAL (481-490)
-- ============================================
('How well do you understand technical project requirements?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 481, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with technical project planning processes?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 482, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your technical project strategies are implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.3, false, 483, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How well do you feel supported in managing technical teams?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 484, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How often do you receive feedback on technical project performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 485, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How manageable is your technical project workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 486, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How well do you feel you can influence technical project direction?', 'JD_R', 'AUTONOMY', 1.3, false, 487, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How often do you feel your technical PM expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 488, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How satisfied are you with technical project management tools?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 489, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),
('How well do you understand how technical projects impact business?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 490, '{"roles": ["project_manager", "tech_pm"], "departments": ["IT", "Engineering"]}'),

-- ============================================
-- SECTION 12: PROJECT MANAGERS - NON-TECHNICAL (491-500)
-- ============================================
('How well do you understand business project requirements?', 'GALLUP_Q12', 'AUTONOMY', 1.2, false, 491, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How satisfied are you with business project planning processes?', 'JD_R', 'WORKLOAD_PRESSURE', 1.2, false, 492, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How often do you feel your business project strategies are implemented?', 'GALLUP_Q12', 'AUTONOMY', 1.3, false, 493, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How well do you feel supported in managing cross-functional teams?', 'JD_R', 'SOCIAL_SUPPORT', 1.2, false, 494, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How often do you receive feedback on business project performance?', 'GALLUP_Q12', 'FEEDBACK_QUALITY', 1.2, false, 495, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How manageable is your business project workload?', 'JD_R', 'WORKLOAD_PRESSURE', 1.3, false, 496, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How well do you feel you can influence business project direction?', 'JD_R', 'AUTONOMY', 1.3, false, 497, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How often do you feel your business PM expertise is recognized?', 'GALLUP_Q12', 'RECOGNITION', 1.2, false, 498, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How satisfied are you with business project management tools?', 'JD_R', 'SOCIAL_SUPPORT', 1.1, false, 499, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}'),
('How well do you understand how business projects impact stakeholders?', 'GALLUP_Q12', 'BELONGING', 1.3, false, 500, '{"roles": ["project_manager", "non_tech_pm"], "departments": ["Operations", "Business"]}')

) AS q(prompt, scale_code, factor_code, weight, reverse_scored, order_index, metadata)
JOIN public.survey_scales s ON s.code = q.scale_code
JOIN public.survey_factors f ON f.code = q.factor_code
ON CONFLICT DO NOTHING;

-- ============================================
-- IMPORT COMPLETE: 500 QUESTIONS
-- ============================================
-- This file contains 500 questions covering:
-- 1. General IT & Staffing (1-50)
-- 2. HR & Recruitment (51-100)
-- 3. Operations (101-150)
-- 4. Full Stack Developers (151-200)
-- 5. Trainers (201-300)
-- 6. Finance & Accounts (301-350)
-- 7. Architects (351-400)
-- 8. Office Admin (401-420)
-- 9. Delivery Heads (421-440)
-- 10. Sales Heads (441-460)
-- 11. Strategic Leadership/Directors (461-480)
-- 12. Project Managers - Technical (481-490)
-- 13. Project Managers - Non-Technical (491-500)
-- 
-- All questions are mapped to:
-- - Scientific Scales: GALLUP_Q12, UWES, PHQ2, INCLUSION, JD_R
-- - Survey Factors: AUTONOMY, WORKLOAD_PRESSURE, SOCIAL_SUPPORT, 
--   FEEDBACK_QUALITY, BELONGING, WORK_LIFE_BALANCE, RECOGNITION, GROWTH
-- - Role metadata for targeted question selection
-- 
-- Ready to import into Supabase survey_questions table
-- ============================================

